services:
  php:
    container_name: leadforyou-php-fpm
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-leadforyou}:${POSTGRES_PASSWORD:-leadforyou}@database:5432/${POSTGRES_DB:-leadforyou}?serverVersion=16&charset=utf8"
    depends_on:
      - database
    networks:
      - leadforyou_network

  nginx:
    container_name: leadforyou-nginx-server
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - leadforyou_network

  database:
    container_name: leadforyou-database
    image: postgres:16
    restart: always
    tty: true
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - leadforyou_network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-leadforyou}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-leadforyou}
      POSTGRES_USER: ${POSTGRES_USER:-leadforyou}

networks:
  leadforyou_network:
    driver: bridge

volumes:
  database-data:
    driver: local