usuario_list:
  path: /user
  controller: App\Controller\UserController::list
  methods: [GET]

usuario_create:
  path: /user
  controller: App\Controller\UserController::create
  methods: [POST]

usuario_update:
  path: /user/{id}
  controller: App\Controller\UserController::update
  methods: [PUT]
